### ISSUE TITLE
Nicks not showing up in mumble?

### ISSUE THREAD

**Issue by surfrock66** [Programie/MatterBukkit#2]
I'm using Paper for 1.16.5, v722 as my Minecraft server, and plugin v 1.3.  I have a murmur server on Ubuntu, the same box as the minecraft server.  It's working well, I can see "matterbridge" in my mumble server, and if I type a message in mumble, I see it in the minecraft server, and vice versa.

The issue is, if a player in game says something, to the Mumble server, I just get the message from "matterbridge" in mumble.  Is there a way to prepend the player name for messages coming from minecraft?  I don't see it in the config.

Looking at the code, I see that the send event is "matterBridgeApi.sendMessage(new Message(player.getName(), event.getMessage(), playerAvatarUrl));" which should send the nick, but I'm not receiving it.  I am guessing this is a config issue with the matterbridge API?  I don't see documentation for what is needed, but that's where I'm looking.

**Comment by Programie** [comment]
I don't have any experience with Mumble. I guess, Matterbridge connected to Mumble is just some kind of user (or a bot which is kind of a regular user with some other rights)?

AFAIK, this would allow Mumble to allow users to "fake" the username of the user who sent the message.

Example:

* You have two players on your Minecraft Server: PlayerA and PlayerB
* PlayerA sends a message "hello"
* MatterBukkit sends the message to MatterBridge
* MatterBridge sends the message to Mumble on behalf of PlayerA (instead of some bot user like "MyMinecraftServer")

Or do you simply want to include the player name in the message sent to Mumble, i.e. like "[PlayerA] hello"?

In that case it should already work by specifying `RemoteNickFormat` containing the `{NICK}` placeholder in your Mumble config in MatterBridge.

Example: `RemoteNickFormat="<{NICK}> "`

**Comment by surfrock66** [comment]
The latter, I'd like the text of the message to indicate who from the minecraft server said it. It sounds like the remoteNickFormat thing should be the key, however it's not working.  The default config was this:

```
[api.myapi]
        BindAddress="127.0.0.1:4242"
        Buffer=1000
        RemoteNickFormat="{NICK}"
        Token="***"
```

But I also tried this

```
[api.myapi]
        BindAddress="127.0.0.1:4242"
        Buffer=1000
        RemoteNickFormat="[{NICK}] "
        Token="***"
```

And neither is working.  I receive messages, but the format is just "matterbridge: test" in the mumble chat.  I don't have another service to integrate right now, just mumble and minecraft, so I'm not sure where to see the issue.  If I'm right, the messages are getting cleared so fast I can't check the /messages api with curl, I always get empty brackets.  I'm pretty new to this, so I'm not sure how to troubleshoot further.

**Comment by surfrock66** [comment]
I got it sorted, I needed that stanza in the mumble config, not the api config.  Derp, got it sorted!
